### ISSUE TITLE
CI cannot run JUnit Tests

### ISSUE THREAD

**Issue by PHameete** [IVCTool/IVCT_Framework#123]
Currently, the Travis-CI can not run unit tests for the IVCT_Framework.

For example, we get stuck on running tests for the Command subproject:

- It requires IVCT_CONF to be set. Aka we need a valid IVCT Runtime folder.
- It requires the HelloWorld TestSuite, which is a different repository alltogether.

I am wondering whether these tests are actually unit tests, or should rather be considered as integration tests? For now I am running the CI build without running tests.

The question is now: do we want to automatically run unit/integration tests with the Travis-CI builds? I am inclined to say yes. If so:

1. Can we remove the dependency of the unit tests on specific Test Suites and an IVCT Runtime configuration?
2. If not: we have a chicken and egg problem: if we have the required docker images for the HelloWorld Test Suite, and the volume containers for making a valid IVCT Runtime, we could set up a valid environment by using docker.

Please let me know what would be possible.

**Comment by rhzg** [comment]
check is this is still an open issue

**Comment by PHameete** [comment]
It still is. You can try it yourself with a `gradle test` on the development branch. Gives an error at:

```
> Task :Command:test

Unexpected exception thrown.
org.gradle.internal.remote.internal.MessageIOException: Could not write '/127.0.0.1:63103'.
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:134)
        at org.gradle.internal.remote.internal.hub.MessageHub$ConnectionDispatch.run(MessageHub.java:325)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.write0(Native Method)
        at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:51)
        at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
        at sun.nio.ch.IOUtil.write(IOUtil.java:51)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeWithNonBlockingRetry(SocketConnection.java:272)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.writeBufferToChannel(SocketConnection.java:260)
        at org.gradle.internal.remote.internal.inet.SocketConnection$SocketOutputStream.flush(SocketConnection.java:254)
        at org.gradle.internal.remote.internal.inet.SocketConnection.flush(SocketConnection.java:132)
        ... 7 more

> Task :Command:test FAILED
```

**Comment by rhzg** [comment]
has been fixed by adding the activemq task into the gradle test build environment
