### ISSUE TITLE
RTI settings not picked up by runner

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#192]
Although the IVCT web UI shows `localhost` for the rtiHostName in the TC parameters, I see an error when running the ICVT. The TC Runner (or actually the LRC) uses the default address `crc` rather than `localhost`.

Work around is to use LRC environment variable `PITCH_CRCADDRESS` to change the address.

````
logsink_1                |
tc-runner_1              | 2019-04-12 10:38:21,606 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: connect exception=Address 'tcp:crc/8989' is unknown/invalid.
logsink_1                | 2019-04-12 10:38:21,611 LogSink: [ERROR] connect exception=Address 'tcp:crc/8989' is unknown/invalid.
tc-runner_1              | 2019-04-12 10:38:21,620 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: initiateRti:
tc-runner_1              | hla.rti1516e.exceptions.ConnectionFailed: Address 'tcp:crc/8989' is unknown/invalid.
tc-runner_1              |      at se.pitch.prti1516e.lrc.p.<init>(prticore_b2920:314) ~[prticore.jar:na]
tc-runner_1              |      at se.pitch.prti1516e.lrc.p.a(prticore_b2920:606) ~[prticore.jar:na]
tc-runner_1              |      at se.pitch.prti1516e.lrc.H.connect(prticore_b2920:48) ~[prticore.jar:na]
tc-runner_1              |      at se.pitch.prti1516e.lrc.H.connect(prticore_b2920:72) ~[prticore.jar:na]
tc-runner_1              |      at se.pitch.prti1516e.lrc.G.connect(prticore_b2920:100) ~[prticore.jar:na]
tc-runner_1              |      at se.pitch.prti1516e.lrc.J.connect(prticore_b2920:570) ~[prticore.jar:na]
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib.IVCT_RTIambassador.connect(IVCT_RTIambassador.java:226) ~[TC.lib-1.0.1.jar:na]
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib.IVCT_BaseModel.initiateRti(IVCT_BaseModel.java:82) ~[TC.lib-1.0.1.jar:na]
tc-runner_1              |      at de.fraunhofer.iosb.tc_encodingrulestester.TC0002.preambleAction(TC0002.java:100) [TS_HLA_EncodingRulesTester-1.0.1.jar:na]
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:137) [TC.lib-1.0.1.jar:na]
tc-runner_1              |      at de.fraunhofer.iosb.testrunner.TestRunner.executeTests(TestRunner.java:78) [TC.exec-1.0.1.jar:na]
tc-runner_1              |      at de.fraunhofer.iosb.testrunner.JMSTestRunner$TestScheduleRunner.run(JMSTestRunner.java:188) [TC.exec-1.0.1.jar:na]
tc-runner_1              |      at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111-internal]
logsink_1                | 2019-04-12 10:38:21,628 LogSink: [ERROR] initiateRti:
tc-runner_1              | 2019-04-12 10:38:21,633 de.fraunhofer.iosb.tc_encodingrulestester.TC0002: getAttributeHandleSetFactory exception=getAttributeHandleSetFactory (909001001)
tc-runner_1              | hla.rti1516e.exceptions.NotConnected: getAttributeHandleSetFactory (909001001)
tc-runner_1              |      at se.pitch.prti1516e.lrc.H.getAttributeHandleSetFactory(prticore_b2920:1388)
logsink_1                | 2019-04-12 10:38:21,636 LogSink: [ERROR] getAttributeHandleSetFactory exception=getAttributeHandleSetFactory (909001001)
tc-runner_1              |      at se.pitch.prti1516e.lrc.G.getAttributeHandleSetFactory(prticore_b2920:8933)
tc-runner_1              |      at se.pitch.prti1516e.lrc.J.getAttributeHandleSetFactory(prticore_b2920:4616)
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib.IVCT_RTIambassador.getAttributeHandleSetFactory(IVCT_RTIambassador.java:2243)
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib_encodingrulestester.DataTreeBuilder.<init>(DataTreeBuilder.java:77)
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib_encodingrulestester.EncodingRulesTesterBaseModel.processSOM(EncodingRulesTesterBaseModel.java:499)
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib_encodingrulestester.EncodingRulesTesterBaseModel.init(EncodingRulesTesterBaseModel.java:320)
tc-runner_1              |      at de.fraunhofer.iosb.tc_encodingrulestester.TC0002.preambleAction(TC0002.java:103)
tc-runner_1              |      at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:137)
tc-runner_1              |      at de.fraunhofer.iosb.testrunner.TestRunner.executeTests(TestRunner.java:78)
tc-runner_1              |      at de.fraunhofer.iosb.testrunner.JMSTestRunner$TestScheduleRunner.run(JMSTestRunner.java:188)
tc-runner_1              |      at java.lang.Thread.run(Thread.java:745)
````

**Comment by rhzg** [comment]
see #181

**Comment by bergtwvd** [comment]
Will verify.

**Comment by bergtwvd** [comment]
I do not see this issue the latest build anymore. I close the issue.
