### ISSUE TITLE
Stacktrace when running the VTMaK compostion

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#214]
With the VTMaK composition I get the stacktrace below when I start a test case such as for hw_iosb, HLA-Declaration-2017, IR-SOM-00003.

````
tc-runner_1               | Using MAK Technologies' RTI version 4.5f HLA 1516-2010 for GNU C++ version 4.8.5 20150623 (Red Hat 4.8.5-11).
tc-runner_1               | Exception in thread "Thread-2" java.lang.ExceptionInInitializerError
tc-runner_1               |     at nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check.logTestPurpose(TC_001_Publish_Subscribe_Check.java:74)
tc-runner_1               |     at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:127)
tc-runner_1               |     at de.fraunhofer.iosb.testrunner.TestEngine$TestScheduleRunner.run(TestEngine.java:203)
tc-runner_1               |     at java.lang.Thread.run(Thread.java:748)
tc-runner_1               | Caused by: java.lang.NullPointerException
tc-runner_1               |     at java.util.Locale.<init>(Locale.java:648)
tc-runner_1               |     at java.util.Locale.<init>(Locale.java:677)
tc-runner_1               |     at nato.ivct.etc.fr.fctt_common.utils.TextInternationalization.<clinit>(TextInternationalization.java:12)
tc-runner_1               |     ... 4 more
````

May be the same cause as https://github.com/IVCTool/IVCT_Framework/issues/211.

**Comment by ducana** [comment]
The solution to #211 should solve this problem as well.

**Comment by bergtwvd** [comment]
Yes, same as the referenced issue.
