### ISSUE TITLE
Another stacktrace in the IVCT UI

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#222]
Get the following stacktrace for the IVCT UI when running an IVCT composition in a "no-host" setup. 

The used composition file is attached. To run, define your own `.env` file with the DOCKERHOST and IVCTUI_PORT vars): [docker-compose.zip](https://github.com/IVCTool/IVCT_Framework/files/3468316/docker-compose.zip)

````
gui_1                     | 05-Aug-2019 15:24:23.176 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
gui_1                     | 05-Aug-2019 15:24:46.878 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ivct.gui.ui.html##2.1.0-SNAPSHOT.war]
gui_1                     | 05-Aug-2019 15:24:48.183 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
gui_1                     | 05-Aug-2019 15:25:07.826 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ivct.gui.ui.html##2.1.0-SNAPSHOT.war] has finished in [20,947] ms
gui_1                     | 05-Aug-2019 15:25:07.827 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive [/usr/local/tomcat/webapps/ivct.gui.server##2.1.0-SNAPSHOT.war]
gui_1                     | 05-Aug-2019 15:25:08.689 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
gui_1                     | 05-Aug-2019 15:25:09.509 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive [/usr/local/tomcat/webapps/ivct.gui.server##2.1.0-SNAPSHOT.war] has finished in [1,682] ms
gui_1                     | 05-Aug-2019 15:25:09.513 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8080"]
gui_1                     | 05-Aug-2019 15:25:09.537 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 49441 ms
gui_1                     | 05-Aug-2019 15:26:08.952 INFO [Thread-7] org.apache.coyote.AbstractProtocol.pause Pausing ProtocolHandler ["http-nio-8080"]
gui_1                     | 05-Aug-2019 15:26:08.954 INFO [Thread-7] org.apache.catalina.core.StandardService.stopInternal Stopping service [IVCT]
gui_1                     | 05-Aug-2019 15:26:13.290 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ivct.gui.server##2.1.0-SNAPSHOT] is still processing a request that has yet to finish. This is very likely to create a memory leak. You can control the time allowed for requests to finish by using the unloadDelay attribute of the standard Context implementation. Stack trace of request processing thread:[
gui_1                     |  java.lang.Object.wait(Native Method)
gui_1                     |  java.lang.Thread.join(Thread.java:1252)
gui_1                     |  java.lang.Thread.join(Thread.java:1326)
gui_1                     |  java.lang.ApplicationShutdownHooks.runHooks(ApplicationShutdownHooks.java:107)
gui_1                     |  java.lang.ApplicationShutdownHooks$1.run(ApplicationShutdownHooks.java:46)
gui_1                     |  java.lang.Shutdown.runHooks(Shutdown.java:123)
gui_1                     |  java.lang.Shutdown.sequence(Shutdown.java:167)
gui_1                     |  java.lang.Shutdown.exit(Shutdown.java:212)
gui_1                     |  java.lang.Runtime.exit(Runtime.java:109)
gui_1                     |  java.lang.System.exit(System.java:971)
gui_1                     |  de.fraunhofer.iosb.messaginghelpers.PropertyBasedClientSetup.initConnection(PropertyBasedClientSetup.java:181)
gui_1                     |  nato.ivct.commander.Factory.initialize(Factory.java:237)
gui_1                     |  nato.ivct.gui.server.ServerSession.execLoadSession(ServerSession.java:309)
gui_1                     |  org.eclipse.scout.rt.server.AbstractServerSession$LocalServerSessionExtension.execLoadSession(AbstractServerSession.java:213)
gui_1                     |  org.eclipse.scout.rt.server.extension.ServerSessionChains$ServerSessionLoadSessionChain$1.callMethod(ServerSessionChains.java:40)
gui_1                     |  org.eclipse.scout.rt.server.extension.ServerSessionChains$ServerSessionLoadSessionChain$1.callMethod(ServerSessionChains.java:1)
gui_1                     |  org.eclipse.scout.rt.shared.extension.AbstractExtensionChain.callChain(AbstractExtensionChain.java:113)
gui_1                     |  org.eclipse.scout.rt.server.extension.ServerSessionChains$ServerSessionLoadSessionChain.execLoadSession(ServerSessionChains.java:43)
gui_1                     |  org.eclipse.scout.rt.server.AbstractServerSession.interceptLoadSession(AbstractServerSession.java:221)
gui_1                     |  org.eclipse.scout.rt.server.AbstractServerSession.start(AbstractServerSession.java:174)
gui_1                     |  org.eclipse.scout.rt.server.session.ServerSessionProvider.lambda$1(ServerSessionProvider.java:76)
gui_1                     |  org.eclipse.scout.rt.server.session.ServerSessionProvider$$Lambda$125/628332416.call(Unknown Source)
gui_1                     |  org.eclipse.scout.rt.platform.chain.callable.CallableChain$Chain.continueChain(CallableChain.java:227)
gui_1                     |  org.eclipse.scout.rt.platform.transaction.TransactionProcessor.runTxMandatory(TransactionProcessor.java:143)
gui_1                     |  org.eclipse.scout.rt.platform.transaction.TransactionProcessor.intercept(TransactionProcessor.java:73)
gui_1                     |  org.eclipse.scout.rt.platform.chain.callable.CallableChain$Chain.continueChain(CallableChain.java:222)
gui_1                     |  org.eclipse.scout.rt.platform.chain.callable.CallableChain.call(CallableChain.java:170)
gui_1                     |  org.eclipse.scout.rt.platform.context.RunContext.call(RunContext.java:156)
gui_1                     |  org.eclipse.scout.rt.platform.context.RunContext.call(RunContext.java:137)
gui_1                     |  org.eclipse.scout.rt.server.session.ServerSessionProvider.lambda$0(ServerSessionProvider.java:74)
gui_1                     |  org.eclipse.scout.rt.server.session.ServerSessionProvider$$Lambda$121/1824091759.call(Unknown Source)
gui_1                     |  org.eclipse.scout.rt.platform.chain.callable.CallableChain$Chain.continueChain(CallableChain.java:227)
gui_1                     |  org.eclipse.scout.rt.platform.transaction.TransactionProcessor.runTxRequiresNew(TransactionProcessor.java:100)
gui_1                     |  org.eclipse.scout.rt.platform.transaction.TransactionProcessor.intercept(TransactionProcessor.java:69)
gui_1                     |  org.eclipse.scout.rt.platform.chain.callable.CallableChain$Chain.continueChain(CallableChain.java:222)
gui_1                     |  org.eclipse.scout.rt.platform.chain.callable.CallableChain.call(CallableChain.java:170)
gui_1                     |  org.eclipse.scout.rt.platform.context.RunContext.call(RunContext.java:156)
gui_1                     |  org.eclipse.scout.rt.platform.context.RunContext.call(RunContext.java:137)
gui_1                     |  org.eclipse.scout.rt.server.session.ServerSessionProvider.provide(ServerSessionProvider.java:65)
gui_1                     |  org.eclipse.scout.rt.server.session.ServerSessionLifecycleHandler.create(ServerSessionLifecycleHandler.java:40)
gui_1                     |  org.eclipse.scout.rt.server.session.ServerSessionEntry.getOrCreateScoutSession(ServerSessionEntry.java:35)
gui_1                     |  org.eclipse.scout.rt.server.session.ServerSessionCache.getOrCreate(ServerSessionCache.java:66)
gui_1                     |  org.eclipse.scout.rt.server.ServiceTunnelServlet.lookupServerSessionOnHttpSession(ServiceTunnelServlet.java:253)
gui_1                     |  org.eclipse.scout.rt.server.ServiceTunnelServlet.doPost(ServiceTunnelServlet.java:148)
gui_1                     |  org.eclipse.scout.rt.server.ServiceTunnelServlet.lambda$1(ServiceTunnelServlet.java:114)
gui_1                     |  org.eclipse.scout.rt.server.ServiceTunnelServlet$$Lambda$101/564906752.run(Unknown Source)
gui_1                     |  org.eclipse.scout.rt.platform.util.concurrent.Callables.lambda$0(Callables.java:31)
gui_1                     |  org.eclipse.scout.rt.platform.util.concurrent.Callables$$Lambda$102/132023271.call(Unknown Source)
gui_1                     |  org.eclipse.scout.rt.platform.chain.callable.CallableChain$Chain.continueChain(CallableChain.java:227)
gui_1                     |  org.eclipse.scout.rt.platform.transaction.TransactionProcessor.runTxRequiresNew(TransactionProcessor.java:100)
gui_1                     |  org.eclipse.scout.rt.platform.transaction.TransactionProcessor.intercept(TransactionProcessor.java:69)
gui_1                     |  org.eclipse.scout.rt.platform.chain.callable.CallableChain$Chain.continueChain(CallableChain.java:222)
gui_1                     |  org.eclipse.scout.rt.platform.chain.callable.CallableChain.call(CallableChain.java:170)
gui_1                     |  org.eclipse.scout.rt.platform.context.RunContext.call(RunContext.java:156)
gui_1                     |  org.eclipse.scout.rt.platform.context.RunContext.run(RunContext.java:123)
gui_1                     |  org.eclipse.scout.rt.server.ServiceTunnelServlet.doPost(ServiceTunnelServlet.java:112)
gui_1                     |  javax.servlet.http.HttpServlet.service(HttpServlet.java:661)
gui_1                     |  org.eclipse.scout.rt.server.commons.servlet.AbstractHttpServlet.access$0(AbstractHttpServlet.java:1)
gui_1                     |  org.eclipse.scout.rt.server.commons.servlet.AbstractHttpServlet$$Lambda$99/547997007.service(Unknown Source)
gui_1                     |  org.eclipse.scout.rt.server.commons.servlet.AbstractHttpServlet.wrap(AbstractHttpServlet.java:49)
gui_1                     |  org.eclipse.scout.rt.server.commons.servlet.AbstractHttpServlet.service(AbstractHttpServlet.java:38)
gui_1                     |  javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
gui_1                     |  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
gui_1                     |  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
gui_1                     |  org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
gui_1                     |  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
gui_1                     |  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
gui_1                     |  org.eclipse.scout.rt.server.commons.authentication.ServletFilterHelper.lambda$0(ServletFilterHelper.java:159)
gui_1                     |  org.eclipse.scout.rt.server.commons.authentication.ServletFilterHelper$$Lambda$98/967875619.run(Unknown Source)
gui_1                     |  java.security.AccessController.doPrivileged(Native Method)
gui_1                     |  javax.security.auth.Subject.doAs(Subject.java:422)
gui_1                     |  org.eclipse.scout.rt.server.commons.authentication.ServletFilterHelper.continueChainAsSubject(ServletFilterHelper.java:155)
gui_1                     |  org.eclipse.scout.rt.server.commons.authentication.ServiceTunnelAccessTokenAccessController.handle(ServiceTunnelAccessTokenAccessController.java:90)
gui_1                     |  nato.ivct.gui.server.ServerServletFilter.doFilter(ServerServletFilter.java:50)
gui_1                     |  org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
gui_1                     |  org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
gui_1                     |  org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
gui_1                     |  org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
gui_1                     |  org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:493)
gui_1                     |  org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:137)
gui_1                     |  org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
gui_1                     |  org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:660)
gui_1                     |  org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
gui_1                     |  org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
gui_1                     |  org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:798)
gui_1                     |  org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
gui_1                     |  org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:808)
gui_1                     |  org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1498)
gui_1                     |  org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
gui_1                     |  java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
gui_1                     |  java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
gui_1                     |  org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
gui_1                     |  java.lang.Thread.run(Thread.java:748)]
gui_1                     | 05-Aug-2019 15:26:13.293 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesThreads The web application [ivct.gui.server##2.1.0-SNAPSHOT] appears to have started a thread named [ActiveMQ InactivityMonitor ReadCheckTimer] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
gui_1                     |  java.lang.Object.wait(Native Method)
gui_1                     |  java.util.TimerThread.mainLoop(Timer.java:552)
gui_1                     |  java.util.TimerThread.run(Timer.java:505)
gui_1                     | 05-Aug-2019 15:26:13.294 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks Unable to determine string representation of value of type [org.eclipse.scout.rt.shared.ui.UserAgent]
gui_1                     |     java.lang.NullPointerException
gui_1                     |             at org.eclipse.scout.rt.platform.BEANS.opt(BEANS.java:55)
gui_1                     |             at org.eclipse.scout.rt.platform.BEANS.get(BEANS.java:41)
gui_1                     |             at org.eclipse.scout.rt.shared.ui.UserAgent.createIdentifier(UserAgent.java:93)
gui_1                     |             at org.eclipse.scout.rt.shared.ui.UserAgent.toString(UserAgent.java:89)
gui_1                     |             at org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks(WebappClassLoaderBase.java:2021)
gui_1                     |             at org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalsForLeaks(WebappClassLoaderBase.java:1947)
gui_1                     |             at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1616)
gui_1                     |             at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1556)
gui_1                     |             at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:446)
gui_1                     |             at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
gui_1                     |             at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5510)
gui_1                     |             at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
gui_1                     |             at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1439)
gui_1                     |             at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1428)
gui_1                     |             at java.util.concurrent.FutureTask.run(FutureTask.java:266)
gui_1                     |             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
gui_1                     |             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
gui_1                     |             at java.lang.Thread.run(Thread.java:748)
gui_1                     | 05-Aug-2019 15:26:13.295 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ivct.gui.server##2.1.0-SNAPSHOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@56222ffb]) and a value of type [org.eclipse.scout.rt.shared.ui.UserAgent] (value [Unknown]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
gui_1                     | 05-Aug-2019 15:26:13.296 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ivct.gui.server##2.1.0-SNAPSHOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@34c28d3]) and a value of type [org.eclipse.scout.rt.platform.context.PropertyMap] (value [org.eclipse.scout.rt.platform.context.PropertyMap@5309ecd1]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
gui_1                     | 05-Aug-2019 15:26:13.296 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ivct.gui.server##2.1.0-SNAPSHOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@28a9b64c]) and a value of type [org.eclipse.scout.rt.platform.context.RunMonitor] (value [org.eclipse.scout.rt.platform.context.RunMonitor@6fb30955]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
gui_1                     | 05-Aug-2019 15:26:13.297 WARNING [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks Unable to determine string representation of value of type [org.eclipse.scout.rt.server.context.ServerRunContext]
gui_1                     |     java.lang.NullPointerException
gui_1                     |             at org.eclipse.scout.rt.platform.BEANS.opt(BEANS.java:55)
gui_1                     |             at org.eclipse.scout.rt.platform.BEANS.get(BEANS.java:41)
gui_1                     |             at org.eclipse.scout.rt.shared.ui.UserAgent.createIdentifier(UserAgent.java:93)
gui_1                     |             at org.eclipse.scout.rt.shared.ui.UserAgent.toString(UserAgent.java:89)
gui_1                     |             at java.lang.String.valueOf(String.java:2994)
gui_1                     |             at java.lang.StringBuilder.append(StringBuilder.java:131)
gui_1                     |             at java.util.AbstractMap$SimpleEntry.toString(AbstractMap.java:724)
gui_1                     |             at org.eclipse.scout.rt.platform.util.StringUtility.join(StringUtility.java:1407)
gui_1                     |             at org.eclipse.scout.rt.platform.util.StringUtility.join(StringUtility.java:1440)
gui_1                     |             at org.eclipse.scout.rt.platform.util.ToStringBuilder.toString(ToStringBuilder.java:212)
gui_1                     |             at org.eclipse.scout.rt.platform.context.RunContext.toString(RunContext.java:474)
gui_1                     |             at org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks(WebappClassLoaderBase.java:2021)
gui_1                     |             at org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalsForLeaks(WebappClassLoaderBase.java:1947)
gui_1                     |             at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1616)
gui_1                     |             at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1556)
gui_1                     |             at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:446)
gui_1                     |             at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
gui_1                     |             at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5510)
gui_1                     |             at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:226)
gui_1                     |             at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1439)
gui_1                     |             at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1428)
gui_1                     |             at java.util.concurrent.FutureTask.run(FutureTask.java:266)
gui_1                     |             at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
gui_1                     |             at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
gui_1                     |             at java.lang.Thread.run(Thread.java:748)
gui_1                     | 05-Aug-2019 15:26:13.298 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ivct.gui.server##2.1.0-SNAPSHOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@d5baec0]) and a value of type [org.eclipse.scout.rt.server.context.ServerRunContext] (value [Unknown]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
gui_1                     | 05-Aug-2019 15:26:13.299 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ivct.gui.server##2.1.0-SNAPSHOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@2476d55]) and a value of type [org.eclipse.scout.rt.platform.transaction.BasicTransaction] (value [org.eclipse.scout.rt.platform.transaction.BasicTransaction@53a5be0a]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
gui_1                     | 05-Aug-2019 15:26:13.299 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ivct.gui.server##2.1.0-SNAPSHOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@7c6cd6f9]) and a value of type [org.eclipse.scout.rt.server.clientnotification.ClientNotificationCollector] (value [org.eclipse.scout.rt.server.clientnotification.ClientNotificationCollector@3582d0f]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
gui_1                     | 05-Aug-2019 15:26:13.306 SEVERE [localhost-startStop-2] org.apache.catalina.loader.WebappClassLoaderBase.checkThreadLocalMapForLeaks The web application [ivct.gui.server##2.1.0-SNAPSHOT] created a ThreadLocal with key of type [java.lang.ThreadLocal] (value [java.lang.ThreadLocal@41c1fce]) and a value of type [nato.ivct.gui.server.ServerSession] (value [nato.ivct.gui.server.ServerSession@74d66b61[id = 62dac9e3-c537-466f-8d18-32c0dc8eeba9]]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
gui_1                     | 05-Aug-2019 15:26:13.347 INFO [Thread-7] org.apache.coyote.AbstractProtocol.stop Stopping ProtocolHandler ["http-nio-8080"]
gui_1                     | 05-Aug-2019 15:26:18.348 WARNING [Thread-7] org.apache.tomcat.util.net.AbstractEndpoint.shutdownExecutor The executor associated with thread pool [http-nio-8080] has not fully shutdown. Some application threads may still be running.
gui_1                     | 05-Aug-2019 15:26:18.349 INFO [Thread-7] org.apache.coyote.AbstractProtocol.destroy Destroying ProtocolHandler ["http-nio-8080"]
ivctpitch_gui_1 exited with code 255
````

**Comment by bergtwvd** [comment]
After running the IVCT composition a few times, I do not see this stacktrace turning back. So, it is not reproducable. Suggest to leave this for what is it and keep the issue for reference in case it turns back.

**Comment by rhzg** [comment]
@michaeltheis : do we have any race conditions between gui server and client process?

**Comment by rhzg** [comment]
problem has not been seen, so issue seems to be solved
