### ISSUE TITLE
Error in language Locale using Mak composition

### ISSUE THREAD

**Issue by bergtwvd** [IVCTool/IVCT_Framework#225]
I still see an error in the Locale handling, below a snippet from the console output:

````
tc-runner_1               | 2019-08-06 11:50:53,938 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check: Test Case Started
tc-runner_1               | 2019-08-06 11:50:53,940 nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check:
tc-runner_1               | TEST CASE PARAMETERS -------------------------------------- BEGIN
tc-runner_1               | {"somFiles":[{"fileName":"\/root\/conf\/IVCTsut\/hw_iosb\/HLA-Declaration-2017\/HelloWorldSOM.xml"}],"fomFiles":[{"fileName":"\/root\/conf\/IVCTsut\/hw_iosb\/HLA-Declaration-2017\/HelloWorld.xml"}],"resultDirectory":"\/root\/conf\/IVCTsut\/hw_iosb\/HLA-Declaration-2017","testDuration":"60"}
tc-runner_1               | TEST CASE PARAMETERS -------------------------------------- END
tc-runner_1               |
logsink_1                 | 2019-08-06 11:50:53,948 LogSink: 2019-08-06 11:50:53.938+0000: Test Case Started
tc-runner_1               | Exception in thread "Thread-2" java.lang.ExceptionInInitializerError
tc-runner_1               |     at nato.ivct.etc.fr.tc_lib_hla_declaration.HLA_Declaration_TcParam.<init>(HLA_Declaration_TcParam.java:64)
tc-runner_1               |     at nato.ivct.etc.fr.tc_hla_declaration.TC_001_Publish_Subscribe_Check.getIVCT_BaseModel(TC_001_Publish_Subscribe_Check.java:57)
tc-runner_1               |     at de.fraunhofer.iosb.tc_lib.AbstractTestCase.execute(AbstractTestCase.java:114)
tc-runner_1               |     at de.fraunhofer.iosb.testrunner.TestEngine$TestScheduleRunner.run(TestEngine.java:203)
tc-runner_1               |     at java.lang.Thread.run(Thread.java:748)
logsink_1                 | 2019-08-06 11:50:53,953 LogSink: 2019-08-06 11:50:53.940+0000:
logsink_1                 | TEST CASE PARAMETERS -------------------------------------- BEGIN
logsink_1                 | {"somFiles":[{"fileName":"\/root\/conf\/IVCTsut\/hw_iosb\/HLA-Declaration-2017\/HelloWorldSOM.xml"}],"fomFiles":[{"fileName":"\/root\/conf\/IVCTsut\/hw_iosb\/HLA-Declaration-2017\/HelloWorld.xml"}],"resultDirectory":"\/root\/conf\/IVCTsut\/hw_iosb\/HLA-Declaration-2017","testDuration":"60"}
logsink_1                 | TEST CASE PARAMETERS -------------------------------------- END
logsink_1                 |
tc-runner_1               | Caused by: java.lang.NullPointerException
tc-runner_1               |     at java.util.Locale.<init>(Locale.java:648)
tc-runner_1               |     at java.util.Locale.<init>(Locale.java:677)
tc-runner_1               |     at nato.ivct.etc.fr.fctt_common.utils.TextInternationalization.<clinit>(TextInternationalization.java:12)
tc-runner_1               |     ... 5 more
````

I use a VTMaK RTI based composition for the IVCT. I do not start up a SUT, and have not changed the settings designator. Just press Execute for hw_iosb > HLA-Declaration-2017 > IR-SOM-0003.

Thought this was fixed? See https://github.com/IVCTool/IVCT_Framework/issues/214 and https://github.com/IVCTool/IVCT_Framework/issues/211.

**Comment by rhzg** [comment]
tested with versions below and issue seems to be solved

IVCT_VERSION=3.0.0
TS_HW_VERSION=2.1.1
TS_HLA_VERSION=2.1.0
